name: Publishing the action to the marketplace

on:   
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    
    
jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          user: rajbos
        id: load-actions

      - run: echo ${{ steps.load-actions.outputs.actions }} > 'actions.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions.json
    
  publish:
    needs: test-local-action
    runs-on: ubuntu-latest
    steps:
      
      - name: Get tag value
        id: tag
        uses: dawidd6/action-get-tag@v1
        
      - name: Use tag
        run: echo ${{ steps.tag.outputs.tag }}

      # - uses: actions/create-release@v1
      #   # todo: this action is no longer supported and has issues with not checking the release name for length
      #   # See example with issue here: https://github.com/rajbos/github-action-load-available-actions/releases/edit/v1.2.3
      #   # find a different action to use        id: create_release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }} 
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Release ${{ steps.tag.outputs.tag }} is available now
      #     draft: false
      #     prerelease: false

      # todo: figure out how this works with an action :-)
      # - uses: actions/publish-release-asset@v2
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
      #     asset_path: ./dist/main.js
      #     asset_name: main.js
      #     asset_content_type: application/javascript

      - uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: Release ${{ steps.tag.outputs.tag }} is available now
          files: ./dist/main.js
          token: ${{ secrets.PAT }}