name: Testing the action

on: 
  push: 

  workflow_dispatch:
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test-load-all-available-actions: # test the action locally without building
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: rajbos/github-action-load-available-actions@typescript
        name: Load used actions
        with: 
          PAT: ${{ secrets.GITHUB_TOKEN }}
        id: load-actions

      - run: echo ${{ steps.load-actions.outputs.actions }} > 'actions.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions.json