name: Testing the action

on: 
  push:

  workflow_dispatch:
    
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # don't run on PRs
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all

  test-load-from-user: # test the action for the user space
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }} # really not clear why GITHUB_TOKEN is not working
          # see docs here: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-1-passing-the-github_token-as-an-input
          user: rajbos
        id: load-actions

      - name: Store output in result file
        if: 1 == 2
        run: echo '${{ steps.load-actions.outputs.actions }}' > 'actions-user.json'
       
      - uses: devops-actions/json-to-file@97145f60f3535b7f016205e5f79934bf5bdcbd41
        with: 
          #json: ${{ steps.load-actions.outputs.actions }}'
          #filename: 'actions-user.json'
          milliseconds: 10
        
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions-user.json
  
  test-load-from-organization: # test the action for the organization space
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' # don't run on PRs
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.PAT }}
          organization: rajbos-actions
        id: load-actions

      - name: Store output in result file
        run: echo '${{ steps.load-actions.outputs.actions }}' > 'actions-organization.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions-organization
          path: actions-organization.json
