name: Testing the action

on: 
  push: 

  workflow_dispatch:
    
jobs:
  load-all-used-actions:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: ./
        name: Load used actions
        with: 
          PAT: ${{ secrets.GITHUB_TOKEN }}
        id: load-actions

      - run: echo ${{ steps.load-actions.outputs.actions }} > 'actions.json'
            
      - name: Upload result file as artefact
        uses: actions/upload-artifact@v2
        with: 
          name: actions
          path: actions.json